### PR TITLE
feat: removable controller

### PR DESCRIPTION
**Pull request by CiTroNaK**
I am not quite sure, that this will be the solution you have expected (#1).

So, let me know, what do you think about this solution :-)

### CODE REVIEW

**Comment by CiTroNaK** [comment]
So, I found a better solution, so I will change it...

**Comment by guillaumebriday** [comment]
Hey thanks a lot @CiTroNaK 

I was thinking to implement something like that : https://github.com/gorails-screencasts/dynamic-nested-forms-with-stimulusjs/blob/master/app/javascript/controllers/nested_form_controller.js#L36

**Comment by CiTroNaK** [comment]
@guillaumebriday yeah, I found it too... (my friend send it to me). I did a few changes to this solution but it is still heavily inspired. It is a pity that he did not publish it as an NPM package.

**Comment by guillaumebriday** [comment]
I did that here https://github.com/stimulus-components/stimulus-rails-nested-form/pull/3

**Comment by guillaumebriday** [comment]
Thanks @CiTroNaK for the work though! 🙏

**Pull request closed without merging**
